### PR TITLE
Resolve Issue #9: Add NFL Score Data

### PR DESCRIPTION
**Pull request by mattb555**
Displays game score of current NFL week of a single team in options as well as simple game clock.

I use [this XML Feed](http://www.nfl.com/liveupdate/scorestrip/ss.xml) for the Data. At present if the game isn't on I just say "Not Live" rather than specifying finished or  because I don't know the code for "final".

Added in required options, HTML, and JS.

### CODE REVIEW

**Comment by mattb555** [comment]
Not gonna lie, it's a little bit funky right now, the Pats/Giants game just went to half and that caused it to just say "Not Live". Once I know the code for Final I'm going to push a commit so it will differentiate pre-game/halftime/post-game.

**Comment by mikedupuis** [comment]
This is great! I will wait to merge it until you push that final change. One other improvement would be to have a dropdown in the options for the team, rather than a text input. If you'd rather not tackle that then just let me know and I'll add it as another issue for someone else to have a look at.

Thank you so much for the PR!!

**Comment by mattb555** [comment]
Ok I added some more informational stuff about game time, also changed team select to a dropdown.

**Comment by mikedupuis** [comment]
Very good! Thank you so much for your contribution!

**Comment by mikedupuis** [comment]
Please feel free to make another PR with an update to contributors.md with a link to your github profile if you wish

**Comment by mattb555** [comment]
Sure, thanks

**Pull request merged**
