### PR TITLE
Adding upcoming birthdays

### PR DESCRIPTION
**Pull request by gcmartins11**
Final version 100% complete v2
(Hope you like it 😛 )

### CODE REVIEW

**Comment by mikedupuis** [comment]
I checked out the code and give it a spin on my browser. Overall, I think it looks pretty good. One thing though, it looks like you are not doing anything with the "I want to see the upcoming birthdays with X days in advance" value, and data doesn't populate on the new tab page. Did you forget to commit some of your changes?

**Comment by gcmartins11** [comment]
I don't think so... but i can give a look if you want! And add some comments too

**Comment by mikedupuis** [comment]
What is the expectation for the UI? I assume that if I have a birthday coming up in 10 days and I set the app to alert me within 14 days, then I should see that birthday in the new tab page. Currently that's not what I see, because there is no logic to store that 14 day threshold, nor is there logic to add anything to the new tab page. What you have is a great start towards that, I just need to know if you intend to keep working on those things or if you want me to merge the PR as-is and have someone else continue working on this functionality through another PR.

**Comment by gcmartins11** [comment]
Hey, well.. Sorry about that, to be honest, it was intended to be (almost) fully functional from the beginning, and I thought that was working properly when i commited my changes, i even asked a friend to give a look and see if was everything okay.
The expectation for the ui was to set in how many days do you want to see the upcomming birthdays, and all the birthdays within that time span would show up in the "Upcoming birthdays" section on the side bar.
I'm sorry for the troubles with this pull request, I'm a beginner on contribuiting for other repositories, but i can try to fix them if you want.

**Comment by mikedupuis** [comment]
No, please don't take it the wrong way. Your contribution is great, I really like the style and I love the implementation. I just want to make sure that everything you intend to be in the PR is actually here.

> The expectation for the ui was to set in how many days do you want to see the upcomming birthdays, and all the birthdays within that time span would show up in the "Upcoming birthdays" section on the side bar.

If this is what you're seeing when you run the extension locally, then I think there is something missing in the PR. Can you double check this?

> I'm sorry for the troubles with this pull request

Don't be sorry, I'm super thankful that you're here. I'm sorry if my comments came off a little harsh.

> I'm a beginner on contribuiting for other repositories

That's okay! I am a beginner at accepting contributions from others. I feel so honored to have you invest your time on this repo. It really means a lot to me. This is a learning experience for everyone.

The takeaway here is:
1. Great job on your work so far!
2. If you have submitted everything you've got on this, that's super, I will accept your PR.
3. If you have more to submit, that's also super and I will hold off. I really just want to make sure that the feature is where you want it to be.

**Comment by gcmartins11** [comment]
Wow, thanks for being so nice!
I actually want to work more on this feature.
I want it to let the user save all the birthdays that he wants, that, that he can set the time span on wich the birthdays will show up, and let him configure the format of date that will be displayed

**Comment by mikedupuis** [comment]
Okay, just let me know if there is anything I can do to help :)

**Comment by mikedupuis** [comment]
Hey @gcmartins11 are you still working on this? Is there anything I can do to help?

**Comment by gcmartins11** [comment]
Hey @mikedupuis, sorry if i'm tooking so long to do this. Thanks for offering to help, but my problem is acctualy with my time, i'm finishing a course this year, and i have a huge project to finish, but i'll try to take a weekend just to finish this task.

**Comment by mikedupuis** [comment]
No worries. Just wanted to make sure you're still working on it :). Again, please let me know if I can help.

**Comment by mikedupuis** [comment]
Closing as there has been a year without any activity.

**Pull request closed without merging**
